spring:
  main:
    allow-circular-references: true
  application:
    name: Project Manage
  datasource:
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
    url: "jdbc:postgresql://localhost:5432/manage-project"
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
    database: postgresql
  mail:
    host: smtp.gmail.com
    username: nhanphmhoang@gmail.com
    password: hthv tcdw huhd ngdl
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
    port: 587